[package]
name = "Peer-to-peer tutoring system"
version = "1.0.0"
authors = []

[addresses]
peer-to-peerTutoringSystem = '0xb9dd7ffd9b1eef6353689fe4551374478f413b095e75a7d2180df2d3030df936'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]  

